INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (1,'Andorra','AD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (2,'Vereinigte Arabische Emirate','AE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (3,'Afghanistan','AF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (4,'Antigua und Barbuda','AG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (5,'Anguilla','AI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (6,'Albanien','AL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (7,'Armenien','AM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (8,'Niederländische Antillen','AN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (9,'Angola','AO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (10,'Antarktis','AQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (11,'Argentinien','AR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (12,'Amerikanisch-Samoa','AS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (13,'Österreich','AT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (14,'Australien','AU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (15,'Aruba','AW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (16,'Åland','AX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (17,'Aserbaidschan','AZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (18,'Bosnien und Herzegowina','BA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (19,'Barbados','BB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (20,'Bangladesch','BD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (21,'Belgien','BE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (22,'Burkina Faso','BF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (23,'Bulgarien','BG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (24,'Bahrain','BH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (25,'Burundi','BI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (26,'Benin','BJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (27,'Bermuda','BM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (28,'Brunei Darussalam','BN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (29,'Bolivien','BO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (30,'Brasilien','BR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (31,'Bahamas','BS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (32,'Bhutan','BT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (33,'Bouvetinsel','BV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (34,'Botswana','BW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (35,'Belarus (Weißrussland)','BY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (36,'Belize','BZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (37,'Kanada','CA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (38,'Kokosinseln (Keelinginseln)','CC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (39,'Kongo','CD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (40,'Zentralafrikanische Republik','CF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (41,'Republik Kongo','CG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (42,'Schweiz','CH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (43,'Elfenbeinküste','CI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (44,'Cookinseln','CK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (45,'Chile','CL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (46,'Kamerun','CM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (47,'China, Volksrepublik','CN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (48,'Kolumbien','CO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (49,'Costa Rica','CR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (50,'Kuba','CU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (51,'Kap Verde','CV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (52,'Weihnachtsinsel','CX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (53,'Zypern','CY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (54,'Tschechische Republik','CZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (55,'Deutschland','DE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (56,'Dschibuti','DJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (57,'Dänemark','DK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (58,'Dominica','DM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (59,'Dominikanische Republik','DO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (60,'Algerien','DZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (61,'Ecuador','EC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (62,'Estland (Reval)','EE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (63,'Ägypten','EG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (64,'Westsahara','EH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (65,'Eritrea','ER');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (66,'Spanien','ES');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (67,'Äthiopien','ET');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (68,'Finnland','FI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (69,'Fidschi','FJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (70,'Falklandinseln (Malwinen)','FK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (71,'Mikronesien','FM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (72,'Färöer','FO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (73,'Frankreich','FR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (74,'Gabun','GA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (75,'Großbritannien und Nordirland','GB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (76,'Grenada','GD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (77,'Georgien','GE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (78,'Französisch-Guayana','GF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (79,'Guernsey (Kanalinsel)','GG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (80,'Ghana','GH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (81,'Gibraltar','GI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (82,'Grönland','GL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (83,'Gambia','GM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (84,'Guinea','GN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (85,'Guadeloupe','GP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (86,'Äquatorialguinea','GQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (87,'Griechenland','GR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (88,'Südgeorgien und die Südl. Sandwichinseln','GS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (89,'Guatemala','GT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (90,'Guam','GU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (91,'Guinea-Bissau','GW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (92,'Guyana','GY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (93,'Hongkong','HK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (94,'Heard- und McDonald-Inseln','HM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (95,'Honduras','HN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (96,'Kroatien','HR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (97,'Haiti','HT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (98,'Ungarn','HU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (99,'Indonesien','ID');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (100,'Irland','IE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (101,'Israel','IL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (102,'Insel Man','IM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (103,'Indien','IN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (104,'Britisches Territorium im Indischen Ozean','IO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (105,'Irak','IQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (106,'Iran','IR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (107,'Island','IS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (108,'Italien','IT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (109,'Jersey (Kanalinsel)','JE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (110,'Jamaika','JM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (111,'Jordanien','JO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (112,'Japan','JP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (113,'Kenia','KE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (114,'Kirgisistan','KG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (115,'Kambodscha','KH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (116,'Kiribati','KI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (117,'Komoren','KM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (118,'St. Kitts und Nevis','KN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (119,'Nordkorea','KP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (120,'Südkorea','KR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (121,'Kuwait','KW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (122,'Kaimaninseln','KY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (123,'Kasachstan','KZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (124,'Laos','LA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (125,'Libanon','LB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (126,'St. Lucia','LC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (127,'Liechtenstein','LI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (128,'Sri Lanka','LK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (129,'Liberia','LR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (130,'Lesotho','LS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (131,'Litauen','LT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (132,'Luxemburg','LU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (133,'Lettland','LV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (134,'Libyen','LY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (135,'Marokko','MA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (136,'Monaco','MC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (137,'Moldawien','MD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (138,'Madagaskar','MG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (139,'Marshallinseln','MH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (140,'Mazedonien','MK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (141,'Mali','ML');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (142,'Myanmar (Burma)','MM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (143,'Mongolei','MN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (144,'Macau','MO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (145,'Nördliche Marianen','MP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (146,'Martinique','MQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (147,'Mauretanien','MR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (148,'Montserrat','MS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (149,'Malta','MT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (150,'Mauritius','MU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (151,'Malediven','MV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (152,'Malawi','MW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (153,'Mexiko','MX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (154,'Malaysia','MY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (155,'Mosambik','MZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (156,'Namibia','NA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (157,'Neukaledonien','NC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (158,'Niger','NE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (159,'Norfolkinsel','NF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (160,'Nigeria','NG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (161,'Nicaragua','NI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (162,'Niederlande','NL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (163,'Norwegen','NO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (164,'Nepal','NP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (165,'Nauru','NR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (166,'Niue','NU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (167,'Neuseeland','NZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (168,'Oman','OM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (169,'Panama','PA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (170,'Peru','PE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (171,'Französisch-Polynesien','PF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (172,'Papua-Neuguinea','PG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (173,'Philippinen','PH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (174,'Pakistan','PK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (175,'Polen','PL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (176,'St. Pierre und Miquelon','PM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (177,'Pitcairninseln','PN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (178,'Puerto Rico','PR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (179,'Palästina','PS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (180,'Portugal','PT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (181,'Palau','PW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (182,'Paraguay','PY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (183,'Katar','QA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (184,'Réunion','RE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (185,'Rumänien','RO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (186,'Russische Föderation','RU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (187,'Ruanda','RW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (188,'Saudi-Arabien','SA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (189,'Salomonen','SB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (190,'Seychellen','SC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (191,'Sudan','SD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (192,'Schweden','SE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (193,'Singapur','SG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (194,'St. Helena','SH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (195,'Slowenien','SI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (196,'Svalbard und Jan Mayen','SJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (197,'Slowakei','SK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (198,'Sierra Leone','SL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (199,'San Marino','SM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (200,'Senegal','SN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (201,'Somalia','SO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (202,'Suriname','SR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (203,'São Tomé und Príncipe','ST');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (204,'El Salvador','SV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (205,'Syrien','SY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (206,'Swasiland','SZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (207,'Turks- und Caicosinseln','TC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (208,'Tschad','TD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (209,'Französische Süd- und Antarktisgebiete','TF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (210,'Togo','TG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (211,'Thailand','TH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (212,'Tadschikistan','TJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (213,'Tokelau','TK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (214,'Timor-Leste','TL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (215,'Turkmenistan','TM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (216,'Tunesien','TN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (217,'Tonga','TO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (218,'Türkei','TR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (219,'Trinidad und Tobago','TT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (220,'Tuvalu','TV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (221,'Taiwan','TW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (222,'Tansania','TZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (223,'Ukraine','UA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (224,'Uganda','UG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (225,'Amerikanisch-Ozeanien','UM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (226,'Vereinigte Staaten von Amerika','US');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (227,'Uruguay','UY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (228,'Usbekistan','UZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (229,'Vatikanstadt','VA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (230,'St. Vincent und die Grenadinen','VC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (231,'Venezuela','VE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (232,'Britische Jungferninseln','VG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (233,'Amerikanische Jungferninseln','VI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (234,'Vietnam','VN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (235,'Vanuatu','VU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (236,'Wallis und Futuna','WF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (237,'Samoa','WS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (238,'Jemen','YE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (239,'Mayotte','YT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (240,'Südafrika','ZA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (241,'Sambia','ZM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (242,'Simbabwe','ZW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (243,'Serbien','RS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (244,'Montenegro','ME');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (245,'Saint-Barthélemy','BL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (246,'Bonaire, Sint Eustatius und Saba','BQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (247,'Curaçao','CW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (248,'Saint-Martin (franz. Teil)','MF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (249,'Sint Maarten (niederl. Teil)','SX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (250,'Sudsudan!Südsudan','SS');
