version: "3.4"
services:
  api:
    build:
      context: ../../../
      dockerfile: docker/src/api.Dockerfile
      args:
        - WWW_DATA_USER_ID
        - WWW_DATA_GROUP_ID
      target: development
    ports:
     - ${HOST_HTTP_PORT}:8080
    environment:
      - MYSQL_HOSTNAME=db
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - API_CORS_ALLOWED_ORIGIN=${API_CORS_ALLOWED_ORIGIN}
      - AIRTABLE_API_KEY=${AIRTABLE_API_KEY}
      - TMP_DATABASE_UPDATE_TOKEN=${TMP_DATABASE_UPDATE_TOKEN}
    volumes:
     - ../../../app:/var/www
    extra_hosts:
       - xdebug.remote.host:${XDEBUG_REMOTE_HOST}
    depends_on:
      - db
  db:
    build:
      context: ../../../
      dockerfile: docker/src/db.Dockerfile
      target: development
    ports:
      - ${HOST_MYSQL_PORT}:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}



