version: 0.2
phases:
  install:
    commands:
      - echo install step...
  pre_build:
    commands:
      - echo logging in to AWS ECR...
      - $(aws ecr get-login --no-include-email --region us-central-1)
  build:
    commands:
      - echo build Docker image on `date`
      - docker build -t covid-19-civitech:latest -f Dockerfile_live .
      - docker tag covid-19-civitech:latest <your-ecr-url>/covid-19-civitech:latest
  post_build:
    commands:
      - echo build Docker image complete `date`
      - echo push latest Docker images to ECR...
      - docker push <your-ecr-url>/covid-19-civitech:latest