INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (1,'Andorra','AD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (2,'United Arab Emirates','AE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (3,'Afghanistan','AF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (4,'Antigua and Barbuda','AG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (5,'Anguilla','AI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (6,'Albania','AL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (7,'Armenia','AM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (8,'Netherlands Antilles','AN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (9,'Angola','AO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (10,'Antarctica','AQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (11,'Argentina','AR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (12,'American Samoa','AS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (13,'Austria','AT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (14,'Australia','AU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (15,'Aruba','AW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (16,'Åland Islands','AX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (17,'Azerbaijan','AZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (18,'Bosnia and Herzegovina','BA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (19,'Barbados','BB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (20,'Bangladesh','BD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (21,'Belgium','BE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (22,'Burkina Faso','BF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (23,'Bulgaria','BG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (24,'Bahrain','BH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (25,'Burundi','BI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (26,'Benin','BJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (27,'Bermuda','BM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (28,'Brunei Darussalam','BN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (29,'Bolivia','BO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (30,'Brazil','BR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (31,'Bahamas','BS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (32,'Bhutan','BT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (33,'Bouvet Island','BV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (34,'Botswana','BW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (35,'Belarus','BY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (36,'Belize','BZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (37,'Canada','CA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (38,'Cocos (Keeling) Islands','CC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (39,'The Democratic Republic Of The Congo','CD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (40,'Central African','CF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (41,'Republic of the Congo','CG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (42,'Switzerland','CH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (43,'Côte d\'Ivoire','CI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (44,'Cook Islands','CK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (45,'Chile','CL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (46,'Cameroon','CM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (47,'China','CN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (48,'Colombia','CO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (49,'Costa Rica','CR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (50,'Serbia and Montenegro','CS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (51,'Cuba','CU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (52,'Cape Verde','CV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (53,'Christmas Island','CX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (54,'Cyprus','CY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (55,'Czech Republic','CZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (56,'Germany','DE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (57,'Djibouti','DJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (58,'Denmark','DK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (59,'Dominica','DM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (60,'Dominican Republic','DO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (61,'Algeria','DZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (62,'Ecuador','EC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (63,'Estonia','EE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (64,'Egypt','EG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (65,'Western Sahara','EH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (66,'Eritrea','ER');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (67,'Spain','ES');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (68,'Ethiopia','ET');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (69,'Finland','FI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (70,'Fiji','FJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (71,'Falkland Islands','FK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (72,'Federated States of Micronesia','FM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (73,'Faroe Islands','FO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (74,'France','FR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (75,'Gabon','GA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (76,'United Kingdom','GB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (77,'Grenada','GD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (78,'Georgia','GE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (79,'French Guiana','GF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (80,'Ghana','GH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (81,'Gibraltar','GI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (82,'Greenland','GL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (83,'Gambia','GM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (84,'Guinea','GN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (85,'Guadeloupe','GP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (86,'Equatorial Guinea','GQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (87,'Greece','GR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (88,'South Georgia and the South Sandwich Islands','GS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (89,'Guatemala','GT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (90,'Guam','GU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (91,'Guinea-Bissau','GW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (92,'Guyana','GY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (93,'Hong Kong','HK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (94,'Heard Island and McDonald Islands','HM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (95,'Honduras','HN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (96,'Croatia','HR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (97,'Haiti','HT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (98,'Hungary','HU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (99,'Indonesia','ID');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (100,'Ireland','IE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (101,'Israel','IL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (102,'Isle of Man','IM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (103,'India','IN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (104,'British Indian Ocean Territory','IO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (105,'Iraq','IQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (106,'Islamic Republic of Iran','IR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (107,'Iceland','IS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (108,'Italy','IT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (109,'Jamaica','JM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (110,'Jordan','JO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (111,'Japan','JP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (112,'Kenya','KE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (113,'Kyrgyzstan','KG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (114,'Cambodia','KH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (115,'Kiribati','KI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (116,'Comoros','KM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (117,'Saint Kitts and Nevis','KN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (118,'Democratic People\'s Republic of Korea','KP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (119,'Republic of Korea','KR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (120,'Kuwait','KW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (121,'Cayman Islands','KY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (122,'Kazakhstan','KZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (123,'Lao People\'s Democratic Republic','LA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (124,'Lebanon','LB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (125,'Saint Lucia','LC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (126,'Liechtenstein','LI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (127,'Sri Lanka','LK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (128,'Liberia','LR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (129,'Lesotho','LS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (130,'Lithuania','LT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (131,'Luxembourg','LU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (132,'Latvia','LV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (133,'Libyan Arab Jamahiriya','LY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (134,'Morocco','MA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (135,'Monaco','MC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (136,'Republic of Moldova','MD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (137,'Madagascar','MG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (138,'Marshall Islands','MH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (139,'The Former Yugoslav Republic of Macedonia','MK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (140,'Mali','ML');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (141,'Myanmar','MM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (142,'Mongolia','MN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (143,'Macao','MO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (144,'Northern Mariana Islands','MP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (145,'Martinique','MQ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (146,'Mauritania','MR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (147,'Montserrat','MS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (148,'Malta','MT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (149,'Mauritius','MU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (150,'Maldives','MV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (151,'Malawi','MW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (152,'Mexico','MX');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (153,'Malaysia','MY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (154,'Mozambique','MZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (155,'Namibia','NA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (156,'New Caledonia','NC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (157,'Niger','NE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (158,'Norfolk Island','NF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (159,'Nigeria','NG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (160,'Nicaragua','NI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (161,'Netherlands','NL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (162,'Norway','NO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (163,'Nepal','NP');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (164,'Nauru','NR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (165,'Niue','NU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (166,'New Zealand','NZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (167,'Oman','OM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (168,'Panama','PA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (169,'Peru','PE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (170,'French Polynesia','PF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (171,'Papua New Guinea','PG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (172,'Philippines','PH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (173,'Pakistan','PK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (174,'Poland','PL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (175,'Saint-Pierre and Miquelon','PM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (176,'Pitcairn','PN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (177,'Puerto Rico','PR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (178,'Occupied Palestinian Territory','PS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (179,'Portugal','PT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (180,'Palau','PW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (181,'Paraguay','PY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (182,'Qatar','QA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (183,'Réunion','RE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (184,'Romania','RO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (185,'Russian Federation','RU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (186,'Rwanda','RW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (187,'Saudi Arabia','SA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (188,'Solomon Islands','SB');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (189,'Seychelles','SC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (190,'Sudan','SD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (191,'Sweden','SE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (192,'Singapore','SG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (193,'Saint Helena','SH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (194,'Slovenia','SI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (195,'Svalbard and Jan Mayen','SJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (196,'Slovakia','SK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (197,'Sierra Leone','SL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (198,'San Marino','SM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (199,'Senegal','SN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (200,'Somalia','SO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (201,'Suriname','SR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (202,'South Sudan','SS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (203,'Sao Tome and Principe','ST');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (204,'El Salvador','SV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (205,'Syrian Arab Republic','SY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (206,'Swaziland','SZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (207,'Turks and Caicos Islands','TC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (208,'Chad','TD');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (209,'French Southern Territories','TF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (210,'Togo','TG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (211,'Thailand','TH');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (212,'Tajikistan','TJ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (213,'Tokelau','TK');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (214,'Timor-Leste','TL');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (215,'Turkmenistan','TM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (216,'Tunisia','TN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (217,'Tonga','TO');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (218,'Turkey','TR');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (219,'Trinidad and Tobago','TT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (220,'Tuvalu','TV');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (221,'Taiwan','TW');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (222,'United Republic Of Tanzania','TZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (223,'Ukraine','UA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (224,'Uganda','UG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (225,'United States Minor Outlying Islands','UM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (226,'United States','US');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (227,'Uruguay','UY');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (228,'Uzbekistan','UZ');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (229,'Vatican City State','VA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (230,'Saint Vincent and the Grenadines','VC');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (231,'Venezuela','VE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (232,'British Virgin Islands','VG');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (233,'U.S. Virgin Islands','VI');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (234,'Vietnam','VN');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (235,'Vanuatu','VU');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (236,'Wallis and Futuna','WF');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (237,'Samoa','WS');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (238,'Yemen','YE');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (239,'Mayotte','YT');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (240,'South Africa','ZA');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (241,'Zambia','ZM');
INSERT INTO `country` (`id`,`name`,`iso_3166_code`) VALUES (242,'Zimbabwe','ZW');
